# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ASUTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import subprocess

from PyQt5 import QtCore, QtGui, QtWidgets
from resources import logos
from resources import OrangeBackgroundResources
from resources import MainWindowResources
from resources import MainWindowResourcesResize
from resources import ASUTPResources

from Karatau import Ui_Karatau
from CPPR import Ui_CPPR


class Ui_ASUTP(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 539)
        MainWindow.setMaximumSize(QtCore.QSize(1400, 1000))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/logos/karatau_logo_small___копия-removebg-preview.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout_2 = QtWidgets.QGridLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.wlcomeToAppLabel = QtWidgets.QLabel(self.centralwidget)
        self.wlcomeToAppLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.wlcomeToAppLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.wlcomeToAppLabel.setStyleSheet("QLabel{\n"
"font: 12pt \"Segoe UI Emoji\";\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"\n"
"}")
        self.wlcomeToAppLabel.setObjectName("wlcomeToAppLabel")
        self.verticalLayout_2.addWidget(self.wlcomeToAppLabel, 0, 0)

        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        #self.imageLabel.setGeometry(1000, 100, 645, 400)
        self.imageLabel.setMinimumSize(QtCore.QSize(645, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(1100, 700))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/ASUTP/images/АСУТП/АСУТП.jpg"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel, 1, 0)

        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)

        self.goToSiteButton = QtWidgets.QPushButton(self.centralwidget)
        self.goToSiteButton.setMinimumSize(QtCore.QSize(110, 35))
        self.goToSiteButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.goToSiteButton.setObjectName("goToSiteButton")
        self.gridLayout_2.addWidget(self.goToSiteButton, 0, 1, 1, 1)
        self.goToSiteButton.clicked.connect(self.goToSite)

        self.verticalLayout_2.addLayout(self.gridLayout_2, 2, 0)

        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.goBackButton = QtWidgets.QPushButton(self.centralwidget)
        self.goBackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.goBackButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.goBackButton.setObjectName("goBackButton")
        self.goBackButton.clicked.connect(self.cppr)

        self.verticalLayout.addWidget(self.goBackButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.aSUTPButton = QtWidgets.QPushButton(self.centralwidget)
        self.aSUTPButton.setMinimumSize(QtCore.QSize(0, 40))
        self.aSUTPButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.aSUTPButton.setObjectName("aSUTPButton")
        self.verticalLayout.addWidget(self.aSUTPButton)
        self.aSUTPButton.clicked.connect(self.asutp)

        self.deyatelnostButton = QtWidgets.QPushButton(self.centralwidget)
        self.deyatelnostButton.setMinimumSize(QtCore.QSize(0, 40))
        self.deyatelnostButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.deyatelnostButton.setObjectName("deyatelnostButton")
        self.verticalLayout.addWidget(self.deyatelnostButton)
        self.deyatelnostButton.clicked.connect(self.deyatelnost)

        self.structuraButton = QtWidgets.QPushButton(self.centralwidget)
        self.structuraButton.setMinimumSize(QtCore.QSize(0, 40))
        self.structuraButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.structuraButton.setObjectName("structuraButton")
        self.verticalLayout.addWidget(self.structuraButton)
        self.structuraButton.clicked.connect(self.structura)

        self.typiOborMapButton = QtWidgets.QPushButton(self.centralwidget)
        self.typiOborMapButton.setMinimumSize(QtCore.QSize(0, 40))
        self.typiOborMapButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.typiOborMapButton.setObjectName("typiOborMapButton")
        self.verticalLayout.addWidget(self.typiOborMapButton)
        self.typiOborMapButton.clicked.connect(self.oborudovanie)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)

        self.goToKaratauMapButton = QtWidgets.QPushButton(self.centralwidget)
        self.goToKaratauMapButton.setMinimumSize(QtCore.QSize(0, 70))
        self.goToKaratauMapButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 16pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.goToKaratauMapButton.setObjectName("goToKaratauMapButton")
        self.goToKaratauMapButton.clicked.connect(self.karatauMap)

        self.verticalLayout.addWidget(self.goToKaratauMapButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def asutp(self):
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setMinimumSize(QtCore.QSize(645, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(1100, 700))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/ASUTP/images/АСУТП/АСУТП.jpg"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel, 1, 0)

    def deyatelnost(self):
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setMinimumSize(QtCore.QSize(645, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(1100, 700))
        self.imageLabel.setPixmap(QtGui.QPixmap(":/ASUTP/images/АСУТП/Деятельность.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel, 1, 0)

    def oborudovanie(self):
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setMinimumSize(QtCore.QSize(645, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(1100, 700))
        self.imageLabel.setStyleSheet("background-image: url(:/ASUTP/images/АСУТП/Оборудование.jpg)")
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/ASUTP/images/АСУТП/Оборудование.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel, 1, 0)

    def structura(self):
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setMinimumSize(QtCore.QSize(645, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(1100, 700))
        self.imageLabel.setStyleSheet("background-image: url(:/ASUTP/images/АСУТП/Структура.jpg)")
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/ASUTP/images/АСУТП/Структура.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel, 1, 0)





    def karatauMap(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Karatau()
            self.ui.setupUi(self.window)
           # MainWindow.hide()
            self.window.show()


    def cppr(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_CPPR()
            self.ui.setupUi(self.window)
            self.window.show()

    def goToSite(self):
        script_path = os.path.abspath(__file__)
        script_dir = os.path.split(script_path)[0]
        rel_path = "resources//links//Karatau.url"
        abs_file_path = os.path.join(script_dir, rel_path)
        # os.startfile(abs_file_path)
        # subprocess.call(abs_file_path, shell=True)
        subprocess.Popen(["cmd", "/C", "start " + rel_path], shell=True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Служба АСУ ТП"))
        self.wlcomeToAppLabel.setText(_translate("MainWindow", "   АСУ ТП - Автоматическая Система Управления Технологическим Процессом"))
        self.goToSiteButton.setText(_translate("MainWindow", "   Перейти на сайт   "))
        self.goBackButton.setText(_translate("MainWindow", "  Местоположение  "))
        self.aSUTPButton.setText(_translate("MainWindow", "АСУ ТП"))
        self.deyatelnostButton.setText(_translate("MainWindow", "  Деятельность "))
        self.structuraButton.setText(_translate("MainWindow", "  Структура отдела  "))
        self.typiOborMapButton.setText(_translate("MainWindow", "  Осн. оборудование  "))
        self.goToKaratauMapButton.setText(_translate("MainWindow", "Карта"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ASUTP()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
