# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Global.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import GTPResources
from resources import MapsResizeResources
from Karatau import Ui_Karatau
from UnderConstruction import Ui_UnderConstruction

class Ui_GlobalMap(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("Global Map")
        MainWindow.resize(661, 450)
        MainWindow.setMinimumSize(QtCore.QSize(661, 450))
        MainWindow.setMaximumSize(QtCore.QSize(661, 450))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/MapsResize/images/MapsУмень/Глобальная.jpg)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.labelMap = QtWidgets.QLabel(self.centralwidget)
        self.labelMap.setEnabled(True)
        self.labelMap.setGeometry(QtCore.QRect(0, 0, 761, 481))
        self.labelMap.setMinimumSize(QtCore.QSize(761, 481))
        self.labelMap.setMaximumSize(QtCore.QSize(761, 481))
        self.labelMap.setStyleSheet("background-image:\n"
"url(:/MapsResize/images/MapsУмень/Глобальная.jpg)")
        self.labelMap.setText("")
        self.labelMap.setPixmap(QtGui.QPixmap(":/MapsResize/images/MapsУмень/Глобальная.jpg"))
        self.labelMap.setScaledContents(True)
        self.labelMap.setObjectName("labelMap")
        self.akdalaButton = QtWidgets.QPushButton(self.centralwidget)
        self.akdalaButton.setEnabled(True)
        self.akdalaButton.setGeometry(QtCore.QRect(470, 110, 131, 31))
        self.akdalaButton.setMinimumSize(QtCore.QSize(0, 30))
        self.akdalaButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.akdalaButton.setObjectName("akdalaButton")

        self.karatauButton = QtWidgets.QPushButton(self.centralwidget)
        self.karatauButton.setEnabled(True)
        self.karatauButton.setGeometry(QtCore.QRect(300, 270, 181, 41))
        self.karatauButton.setMinimumSize(QtCore.QSize(0, 30))
        self.karatauButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 16pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:15px;\n"
"}")
        self.karatauButton.setObjectName("karatauButton")
        self.karatauButton.clicked.connect(self.karatau)

        self.akbastauButton = QtWidgets.QPushButton(self.centralwidget)
        self.akbastauButton.setEnabled(True)
        self.akbastauButton.setGeometry(QtCore.QRect(200, 370, 221, 30))
        self.akbastauButton.setMinimumSize(QtCore.QSize(0, 30))
        self.akbastauButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.akbastauButton.setObjectName("akbastauButton")
        self.akbastauButton.clicked.connect(self.underConstruction)

        self.taikonyrButton = QtWidgets.QPushButton(self.centralwidget)
        self.taikonyrButton.setEnabled(True)
        self.taikonyrButton.setGeometry(QtCore.QRect(210, 150, 131, 31))
        self.taikonyrButton.setMinimumSize(QtCore.QSize(0, 30))
        self.taikonyrButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.taikonyrButton.setObjectName("taikonyrButton")
        self.inkaiButton = QtWidgets.QPushButton(self.centralwidget)
        self.inkaiButton.setEnabled(True)
        self.inkaiButton.setGeometry(QtCore.QRect(300, 100, 131, 31))
        self.inkaiButton.setMinimumSize(QtCore.QSize(0, 30))
        self.inkaiButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.inkaiButton.setObjectName("inkaiButton")
        self.minkudukButton = QtWidgets.QPushButton(self.centralwidget)
        self.minkudukButton.setEnabled(True)
        self.minkudukButton.setGeometry(QtCore.QRect(460, 0, 131, 30))
        self.minkudukButton.setMinimumSize(QtCore.QSize(0, 30))
        self.minkudukButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.minkudukButton.setObjectName("minkudukButton")
        self.uzhinkaiButton = QtWidgets.QPushButton(self.centralwidget)
        self.uzhinkaiButton.setEnabled(True)
        self.uzhinkaiButton.setGeometry(QtCore.QRect(220, 220, 171, 31))
        self.uzhinkaiButton.setMinimumSize(QtCore.QSize(0, 30))
        self.uzhinkaiButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.uzhinkaiButton.setObjectName("uzhinkaiButton")
        self.zapminkudukButton = QtWidgets.QPushButton(self.centralwidget)
        self.zapminkudukButton.setEnabled(True)
        self.zapminkudukButton.setGeometry(QtCore.QRect(160, 30, 151, 51))
        self.zapminkudukButton.setMinimumSize(QtCore.QSize(0, 30))
        self.zapminkudukButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.zapminkudukButton.setObjectName("zapminkudukButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionGlobalMap = QtWidgets.QAction(MainWindow)
        self.actionGlobalMap.setObjectName("actionGlobalMap")
        self.actionCPPR = QtWidgets.QAction(MainWindow)
        self.actionCPPR.setObjectName("actionCPPR")
        self.actionAP = QtWidgets.QAction(MainWindow)
        self.actionAP.setObjectName("actionAP")
        self.actionGBK = QtWidgets.QAction(MainWindow)
        self.actionGBK.setObjectName("actionGBK")
        self.actionPoligon = QtWidgets.QAction(MainWindow)
        self.actionPoligon.setObjectName("actionPoligon")
        self.actionRaskomandirovka = QtWidgets.QAction(MainWindow)
        self.actionRaskomandirovka.setObjectName("actionRaskomandirovka")
        self.actionFKhLFirstFloor = QtWidgets.QAction(MainWindow)
        self.actionFKhLFirstFloor.setObjectName("actionFKhLFirstFloor")
        self.actionFKhLSecondFloor = QtWidgets.QAction(MainWindow)
        self.actionFKhLSecondFloor.setObjectName("actionFKhLSecondFloor")
        self.KIPiA = QtWidgets.QAction(MainWindow)
        self.KIPiA.setCheckable(False)
        self.KIPiA.setObjectName("KIPiA")
        self.SGE = QtWidgets.QAction(MainWindow)
        self.SGE.setObjectName("SGE")
        self.SGM = QtWidgets.QAction(MainWindow)
        self.SGM.setObjectName("SGM")
        self.actionKaratauMap = QtWidgets.QAction(MainWindow)
        self.actionKaratauMap.setObjectName("actionKaratauMap")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def karatau(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Karatau()
        self.ui.setupUi(self.window)
        self.window.show()

    def underConstruction(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_UnderConstruction()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Global Map"))
        self.akdalaButton.setText(_translate("MainWindow", "Акдала"))
        self.karatauButton.setText(_translate("MainWindow", "Каратау"))
        self.akbastauButton.setText(_translate("MainWindow", "Акбастау"))
        self.taikonyrButton.setText(_translate("MainWindow", "Тайконур"))
        self.inkaiButton.setText(_translate("MainWindow", "Инкай"))
        self.minkudukButton.setText(_translate("MainWindow", "Мынкудук"))
        self.uzhinkaiButton.setText(_translate("MainWindow", "Южный Инкай"))
        self.zapminkudukButton.setText(_translate("MainWindow", "Зап. Мынкудук"))
        self.actionGlobalMap.setText(_translate("MainWindow", "Глобальная"))
        self.actionCPPR.setText(_translate("MainWindow", "ЦППР"))
        self.actionAP.setText(_translate("MainWindow", "АП"))
        self.actionGBK.setText(_translate("MainWindow", "ГБК"))
        self.actionPoligon.setText(_translate("MainWindow", "Полигон"))
        self.actionRaskomandirovka.setText(_translate("MainWindow", "Раскомандировка"))
        self.actionFKhLFirstFloor.setText(_translate("MainWindow", "Первый этаж"))
        self.actionFKhLSecondFloor.setText(_translate("MainWindow", "Второй этаж"))
        self.KIPiA.setText(_translate("MainWindow", "КИПиА"))
        self.SGE.setText(_translate("MainWindow", "СГЭ"))
        self.SGM.setText(_translate("MainWindow", "СГМ"))
        self.actionKaratauMap.setText(_translate("MainWindow", "Каратау"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_GlobalMap()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
