# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Karatau.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import GTPResources
from resources import MapsResizeResources
from Proizvodstvo import Ui_Proizvodstvo
from Poselok import Ui_Poselok

from resources import OrangeBackgroundResources

class Ui_Karatau(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 450)
        MainWindow.setMinimumSize(QtCore.QSize(661, 450))
        MainWindow.setMaximumSize(QtCore.QSize(661, 450))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/logos/karatau_logo_small___копия-removebg-preview.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")

        self.labelMap = QtWidgets.QLabel(self.centralwidget)
        self.labelMap.setEnabled(True)
        self.labelMap.setGeometry(QtCore.QRect(0, 0, 761, 481))
        self.labelMap.setMinimumSize(QtCore.QSize(761, 481))
        self.labelMap.setMaximumSize(QtCore.QSize(761, 481))
        self.labelMap.setStyleSheet("background-image:url(:/MapsResize/images/MapsУмень/Каратау.jpg)")
        self.labelMap.setText("")
        self.labelMap.setPixmap(QtGui.QPixmap(":/MapsResize/images/MapsУмень/Каратау.jpg"))
        self.labelMap.setScaledContents(True)
        self.labelMap.setObjectName("labelMap")

        self.proizvodstvoButton = QtWidgets.QPushButton(self.centralwidget)
        self.proizvodstvoButton.setEnabled(True)
        self.proizvodstvoButton.setGeometry(QtCore.QRect(450, 90, 151, 31))
        self.proizvodstvoButton.setMinimumSize(QtCore.QSize(0, 30))
        self.proizvodstvoButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.proizvodstvoButton.setObjectName("proizvodstvoButton")
        self.proizvodstvoButton.clicked.connect(self.proizvodstvo)

        self.vakhtoviiPoselokButton = QtWidgets.QPushButton(self.centralwidget)
        self.vakhtoviiPoselokButton.setEnabled(True)
        self.vakhtoviiPoselokButton.setGeometry(QtCore.QRect(40, 240, 211, 31))
        self.vakhtoviiPoselokButton.setMinimumSize(QtCore.QSize(0, 30))
        self.vakhtoviiPoselokButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"                                                  
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.vakhtoviiPoselokButton.setObjectName("vakhtoviiPoselokButton")
        self.vakhtoviiPoselokButton.clicked.connect(self.poselok)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 130, 241, 31))
        self.label.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def proizvodstvo(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Proizvodstvo()
        self.ui.setupUi(self.window)
        self.window.show()

    def poselok(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Poselok()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kаратау"))
        self.proizvodstvoButton.setText(_translate("MainWindow", "Произодство"))
        self.vakhtoviiPoselokButton.setText(_translate("MainWindow", "Вахтовый Поселок"))
        self.label.setText(_translate("MainWindow", "  Поселок РосБорМаш"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Karatau()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())