# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KUB-5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from resources import GTPResources
from resources import logos


class Ui_KUB5(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 513)
        MainWindow.setMinimumSize(QtCore.QSize(517, 513))
        MainWindow.setMaximumSize(QtCore.QSize(517, 513))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/logos/karatau_logo_small___копия-removebg-preview.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.manualButton = QtWidgets.QPushButton(self.centralwidget)
        self.manualButton.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.manualButton.setMinimumSize(QtCore.QSize(0, 30))
        self.manualButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.manualButton.setObjectName("manualButton")
        self.manualButton.clicked.connect(self.manual)
        self.purposeButton = QtWidgets.QPushButton(self.centralwidget)
        self.purposeButton.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.purposeButton.setMinimumSize(QtCore.QSize(0, 30))
        self.purposeButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.purposeButton.setObjectName("purposeButton")
        self.tipsButton = QtWidgets.QPushButton(self.centralwidget)
        self.tipsButton.setGeometry(QtCore.QRect(10, 110, 131, 31))
        self.tipsButton.setMinimumSize(QtCore.QSize(0, 30))
        self.tipsButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.tipsButton.setObjectName("tipsButton")
        self.Logos = QtWidgets.QLabel(self.centralwidget)
        self.Logos.setGeometry(QtCore.QRect(10, 450, 111, 41))
        self.Logos.setStyleSheet("QLabel {url(:/logos/logos-2.png);}")
        self.Logos.setText("")
        self.Logos.setPixmap(QtGui.QPixmap(":/logos/logos-2.png"))
        self.Logos.setScaledContents(True)
        self.Logos.setObjectName("Logos")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 341, 491))
        self.label.setStyleSheet("Background-image:\n"
"url(:/GTP/images/GTP Map/КУБ-5.jpg)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/GTP/images/GTP Map/КУБ-5.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def manual(self):
        import os
        script_path = os.path.abspath(__file__)
        script_dir = os.path.split(script_path)[0]
        rel_path = "resources//manuals//placeholder.pdf"
        abs_file_path = os.path.join(script_dir,rel_path)
        os.startfile(abs_file_path)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manualButton.setText(_translate("MainWindow", "Мануал"))
        self.purposeButton.setText(_translate("MainWindow", "Назначение"))
        self.tipsButton.setText(_translate("MainWindow", "Подсказки"))
"""""
    def manual(self):
        import os
        #os.startfile('C://Users//Charcharadon Astra//Desktop//Питон//Демка//resources//manuals//placeholder.pdf')
        os.startfile('C:\\resources//manuals//placeholder.pdf')
        #import subprocess
        #subprocess.call("placeholder.pdf", shell=True)
"""



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_KUB5()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

