# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

from MainWindow import Ui_MainWindow
from LoginErorMessage import *
from resources import logos
from OtherWindow import Ui_OtherWindow


class Ui_LoginScreen(object):

    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        LoginScreen.resize(450, 350)
        LoginScreen.setMaximumSize(QtCore.QSize(450, 350))

        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(-10, -10, 461, 371))
        self.Background.setStyleSheet("background-color: rgb(65, 102, 245);")
        self.Background.setText("")
        self.Background.setObjectName("Background")

        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(90, 230, 260, 24))
        self.LoginButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}\n"
"\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        #self.LoginButton.setShortcut()
        self.LoginButton.clicked.connect(self.getValues)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 90, 260, 30))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\" ;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Введите логин")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 150, 260, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 250, 5);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 14pt \"Arial\" ;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setPlaceholderText("Введите пароль")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.Corporated = QtWidgets.QLabel(self.centralwidget)
        self.Corporated.setGeometry(QtCore.QRect(320, 320, 141, 21))
        self.Corporated.setStyleSheet("QLabel{\n"
"color: rgb(0, 0, 0);\n"
"    font: 75 11pt \"Bahnschrift Condensed\";\n"
"}")
        self.Corporated.setObjectName("Corporated")

        self.Welcome = QtWidgets.QLabel(self.centralwidget)
        self.Welcome.setGeometry(QtCore.QRect(70, 10, 301, 61))
        self.Welcome.setStyleSheet("QLabel{\n"
"color: rgb(0, 0, 0);\n"
"font: 25pt \"Bahnschrift Condensed\" ;\n"
"}")
        self.Welcome.setObjectName("Welcome")

        self.Logos = QtWidgets.QLabel(self.centralwidget)
        self.Logos.setGeometry(QtCore.QRect(10, 300, 111, 41))
        self.Logos.setStyleSheet("QLabel {url(:/logos/logos-2.png);}")
        self.Logos.setText("")
        self.Logos.setPixmap(QtGui.QPixmap(":/logos/logos-2.png"))
        self.Logos.setScaledContents(True)
        self.Logos.setObjectName("Logos")

        LoginScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Login screen"))
        self.LoginButton.setText(_translate("LoginScreen", "Войти"))
        self.Corporated.setText(_translate("LoginScreen", "ТОО Каратау ©      2021"))
        self.Welcome.setText(_translate("LoginScreen", "        Добро пожаловать"))

    def getValues(self):

        if self.lineEdit.text()=="Karatau" and self.lineEdit_2.text()=="Karatau":
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            MainWindow.hide()
            self.window.show()

        else:
            self.window = QtWidgets.QMainWindow()
            self.ui = ErorWindow()
            self.ui.setupUi(self.window)
            self.window.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginScreen()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
