# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proizvodstvo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import OrangeBackgroundResources
from resources import GTPResources
from resources import MapsResizeResources
from CPPR import Ui_CPPR
from AP import Ui_AP
from TNS import Ui_TNS
from SZhR import Ui_SZhR
from SSR import Ui_SSR
from FKhL import Ui_FKhL
from UnderConstruction import Ui_UnderConstruction


class Ui_Proizvodstvo(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/logos/karatau_logo_small___копия-removebg-preview.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")

        self.labelMap = QtWidgets.QLabel(self.centralwidget)
        self.labelMap.setEnabled(True)
        self.labelMap.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.labelMap.setMinimumSize(QtCore.QSize(800, 500))
        self.labelMap.setMaximumSize(QtCore.QSize(800, 500))
        self.labelMap.setStyleSheet("background-image:url(:/MapsResize/images/MapsУмень/Производство.jpg)")
        self.labelMap.setText("")
        self.labelMap.setPixmap(QtGui.QPixmap(":/MapsResize/images/MapsУмень/Производство.jpg"))
        self.labelMap.setScaledContents(True)
        self.labelMap.setObjectName("labelMap")

        self.cpprButton = QtWidgets.QPushButton(self.centralwidget)
        self.cpprButton.setEnabled(True)
        self.cpprButton.setGeometry(QtCore.QRect(490, 240, 81, 40))
        self.cpprButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cpprButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.cpprButton.setObjectName("cpprButton")
        self.cpprButton.clicked.connect(self.cppr)

        self.centSkladLabel = QtWidgets.QLabel(self.centralwidget)
        self.centSkladLabel.setGeometry(QtCore.QRect(490, 370, 150, 26))
        self.centSkladLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.centSkladLabel.setObjectName("centSkladLabel")

        self.tnsButton = QtWidgets.QPushButton(self.centralwidget)
        self.tnsButton.setEnabled(True)
        self.tnsButton.setGeometry(QtCore.QRect(310, 50, 71, 40))
        self.tnsButton.setMinimumSize(QtCore.QSize(0, 30))
        self.tnsButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.tnsButton.setObjectName("tnsButton")
        self.tnsButton.clicked.connect(self.tns)

        self.apButton = QtWidgets.QPushButton(self.centralwidget)
        self.apButton.setEnabled(True)
        self.apButton.setGeometry(QtCore.QRect(690, 300, 81, 40))
        self.apButton.setMinimumSize(QtCore.QSize(0, 30))
        self.apButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.apButton.setObjectName("apButton")
        self.apButton.clicked.connect(self.ap)

        self.ssrButton = QtWidgets.QPushButton(self.centralwidget)
        self.ssrButton.setEnabled(True)
        self.ssrButton.setGeometry(QtCore.QRect(350, 380, 81, 40))
        self.ssrButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ssrButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.ssrButton.setObjectName("ssrButton")
        self.ssrButton.clicked.connect(self.ssr)

        self.fkhlButton = QtWidgets.QPushButton(self.centralwidget)
        self.fkhlButton.setEnabled(True)
        self.fkhlButton.setGeometry(QtCore.QRect(170, 290, 81, 40))
        self.fkhlButton.setMinimumSize(QtCore.QSize(0, 30))
        self.fkhlButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.fkhlButton.setObjectName("fkhlButton")
        self.fkhlButton.clicked.connect(self.fkhl)

        self.szhrButton = QtWidgets.QPushButton(self.centralwidget)
        self.szhrButton.setEnabled(True)
        self.szhrButton.setGeometry(QtCore.QRect(320, 150, 71, 40))
        self.szhrButton.setMinimumSize(QtCore.QSize(0, 30))
        self.szhrButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.szhrButton.setObjectName("szhrButton")
        self.szhrButton.clicked.connect(self.szhr)

        self.cnsButton = QtWidgets.QPushButton(self.centralwidget)
        self.cnsButton.setEnabled(True)
        self.cnsButton.setGeometry(QtCore.QRect(450, 140, 71, 40))
        self.cnsButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cnsButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"background-image: url(:/orange/images/orangebackgroundbutton.jpg);"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"border-radius:20px;\n"
"}")
        self.cnsButton.setObjectName("cnsButton")
        self.cnsButton.clicked.connect(self.underConstruction)

        self.hbkLabel = QtWidgets.QLabel(self.centralwidget)
        self.hbkLabel.setGeometry(QtCore.QRect(10, 270, 61, 21))
        self.hbkLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.hbkLabel.setObjectName("hbkLabel")

        self.kppLabel = QtWidgets.QLabel(self.centralwidget)
        self.kppLabel.setGeometry(QtCore.QRect(30, 190, 71, 26))
        self.kppLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.kppLabel.setObjectName("kppLabel")

        self.techVodaLabel = QtWidgets.QLabel(self.centralwidget)
        self.techVodaLabel.setGeometry(QtCore.QRect(240, 230, 111, 26))
        self.techVodaLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.techVodaLabel.setObjectName("techVodaLabel")

        self.avtoboksLabel = QtWidgets.QLabel(self.centralwidget)
        self.avtoboksLabel.setGeometry(QtCore.QRect(170, 180, 111, 26))
        self.avtoboksLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.avtoboksLabel.setObjectName("avtoboksLabel")

        self.abkLabel = QtWidgets.QLabel(self.centralwidget)
        self.abkLabel.setGeometry(QtCore.QRect(130, 230, 61, 26))
        self.abkLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.abkLabel.setObjectName("abkLabel")

        self.sukhSkladLabel = QtWidgets.QLabel(self.centralwidget)
        self.sukhSkladLabel.setGeometry(QtCore.QRect(610, 150, 141, 26))
        self.sukhSkladLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.sukhSkladLabel.setObjectName("sukhSkladLabel")

        self.disaktivaciaLabel = QtWidgets.QLabel(self.centralwidget)
        self.disaktivaciaLabel.setGeometry(QtCore.QRect(635, 210, 161, 26))
        self.disaktivaciaLabel.setStyleSheet("background-image: url(:/arrow right/Karatau blue background.png);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"font: 100 14pt \"Arial\" ")
        self.disaktivaciaLabel.setObjectName("disaktivaciaLabel")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def fkhl(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_FKhL()
        self.ui.setupUi(self.window)
        self.window.show()

    def ssr(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SSR()
        self.ui.setupUi(self.window)
        self.window.show()

    def tns(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TNS()
        self.ui.setupUi(self.window)
        self.window.show()

    def szhr(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SZhR()
        self.ui.setupUi(self.window)
        self.window.show()

    def cppr(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CPPR()
        self.ui.setupUi(self.window)
        self.window.show()

    def ap(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AP()
        self.ui.setupUi(self.window)
        self.window.show()

    def underConstruction(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_UnderConstruction()
        self.ui.setupUi(self.window)
        self.window.show()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Производство"))
        self.cpprButton.setText(_translate("MainWindow", "ЦППР"))
        self.centSkladLabel.setText(_translate("MainWindow", "  Цент. Склад"))
        self.tnsButton.setText(_translate("MainWindow", "ТНС"))
        self.apButton.setText(_translate("MainWindow", "АП"))
        self.ssrButton.setText(_translate("MainWindow", "ССР"))
        self.fkhlButton.setText(_translate("MainWindow", "ФХЛ"))
        self.szhrButton.setText(_translate("MainWindow", "СЖР"))
        self.cnsButton.setText(_translate("MainWindow", "ЦНС"))
        self.hbkLabel.setText(_translate("MainWindow", "  ХБК"))
        self.kppLabel.setText(_translate("MainWindow", "  КПП"))
        self.techVodaLabel.setText(_translate("MainWindow", " Тех. Вода"))
        self.avtoboksLabel.setText(_translate("MainWindow", " Автобокс"))
        self.abkLabel.setText(_translate("MainWindow", " АБК"))
        self.sukhSkladLabel.setText(_translate("MainWindow", " Сухой склад"))
        self.disaktivaciaLabel.setText(_translate("MainWindow", " Дизактивация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Proizvodstvo()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
