# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UPRR.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import GTPResources
from resources import logos
from KUB5 import Ui_KUB5


class Ui_UPRR(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('karatauicon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 494)
        MainWindow.setMinimumSize(QtCore.QSize(661, 494))
        MainWindow.setMaximumSize(QtCore.QSize(661, 494))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(65, 102, 245);\n"
"background-image: url(:/logos/karatau_logo_small___копия-removebg-preview.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 761, 481))
        self.label.setMinimumSize(QtCore.QSize(761, 481))
        self.label.setMaximumSize(QtCore.QSize(761, 481))
        self.label.setStyleSheet("background-image:\n"
"url(:/GTP/images/GTP Map/УПРР.jpg)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/GTP/images/GTP Map/УПРР.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.kUB5Button = QtWidgets.QPushButton(self.centralwidget)
        self.kUB5Button.setGeometry(QtCore.QRect(40, 170, 91, 51))
        self.kUB5Button.setMinimumSize(QtCore.QSize(0, 30))
        self.kUB5Button.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(65, 102, 245);\n"
"border-style:outset;\n"
"border-radius:10px;\n"
"font: 100 14pt \"Arial\" ;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 148, 164);\n"
"}")
        self.kUB5Button.setObjectName("kUB5Button")
        self.kUB5Button.setText("КУБ-5")
        self.kUB5Button.clicked.connect(self.kub5)
        MainWindow.setCentralWidget(self.centralwidget)

        """""
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setStyleSheet("QMenuBar{background-color: rgb(246, 250, 5);\n"
"background-image: url(:/arrow right/images/Karatau yellow background.png);\n"
"}\n"
"QMenuBar:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuMaps = QtWidgets.QMenu(self.menubar)
        self.menuMaps.setStyleSheet("QMenu:hover{\n"
"color:rgb(0, 0, 05);\n"
"background-color: rgb(245, 169, 17);\n"
"}")
        self.menuMaps.setObjectName("menuMaps")
        self.menuAboutUs = QtWidgets.QMenu(self.menubar)
        self.menuAboutUs.setObjectName("menuAboutUs")
        self.menuObjects = QtWidgets.QMenu(self.menubar)
        self.menuObjects.setObjectName("menuObjects")
        self.menuActionGTP = QtWidgets.QMenu(self.menuObjects)
        self.menuActionGTP.setObjectName("menuActionGTP")
        self.menuActionFKhL = QtWidgets.QMenu(self.menuObjects)
        self.menuActionFKhL.setObjectName("menuActionFKhL")
        self.menuDepartments = QtWidgets.QMenu(self.menubar)
        self.menuDepartments.setObjectName("menuDepartments")
        self.menuWhatIsIt = QtWidgets.QMenu(self.menubar)
        self.menuWhatIsIt.setObjectName("menuWhatIsIt")
        MainWindow.setMenuBar(self.menubar)
        self.actionGlobalMap = QtWidgets.QAction(MainWindow)
        self.actionGlobalMap.setObjectName("actionGlobalMap")
        self.actionCPPR = QtWidgets.QAction(MainWindow)
        self.actionCPPR.setObjectName("actionCPPR")
        self.actionAP = QtWidgets.QAction(MainWindow)
        self.actionAP.setObjectName("actionAP")
        self.actionGBK = QtWidgets.QAction(MainWindow)
        self.actionGBK.setObjectName("actionGBK")

        self.actionPoligon = QtWidgets.QAction(MainWindow)
        self.actionPoligon.setObjectName("actionPoligon")
        self.actionPoligon.triggered.connect(self.gtpPoligon)

        self.actionRaskomandirovka = QtWidgets.QAction(MainWindow)
        self.actionRaskomandirovka.setObjectName("actionRaskomandirovka")
        self.actionFKhLFirstFloor = QtWidgets.QAction(MainWindow)
        self.actionFKhLFirstFloor.setObjectName("actionFKhLFirstFloor")
        self.actionFKhLSecondFloor = QtWidgets.QAction(MainWindow)
        self.actionFKhLSecondFloor.setObjectName("actionFKhLSecondFloor")
        self.KIPiA = QtWidgets.QAction(MainWindow)
        self.KIPiA.setCheckable(False)
        self.KIPiA.setObjectName("KIPiA")
        self.SGE = QtWidgets.QAction(MainWindow)
        self.SGE.setObjectName("SGE")
        self.SGM = QtWidgets.QAction(MainWindow)
        self.SGM.setObjectName("SGM")
        self.actionKaratauMap = QtWidgets.QAction(MainWindow)
        self.actionKaratauMap.setObjectName("actionKaratauMap")
        self.menuMaps.addAction(self.actionGlobalMap)
        self.menuMaps.addAction(self.actionKaratauMap)
        self.menuActionGTP.addAction(self.actionPoligon)
        self.menuActionGTP.addAction(self.actionRaskomandirovka)
        self.menuActionFKhL.addAction(self.actionFKhLFirstFloor)
        self.menuActionFKhL.addAction(self.actionFKhLSecondFloor)
        self.menuObjects.addAction(self.menuActionGTP.menuAction())
        self.menuObjects.addAction(self.actionCPPR)
        self.menuObjects.addAction(self.actionAP)
        self.menuObjects.addSeparator()
        self.menuObjects.addAction(self.actionGBK)
        self.menuObjects.addAction(self.menuActionFKhL.menuAction())
        self.menuDepartments.addAction(self.KIPiA)
        self.menuDepartments.addAction(self.SGE)
        self.menuDepartments.addAction(self.SGM)
        self.menubar.addAction(self.menuMaps.menuAction())
        self.menubar.addAction(self.menuAboutUs.menuAction())
        self.menubar.addAction(self.menuObjects.menuAction())
        self.menubar.addAction(self.menuDepartments.menuAction())
        self.menubar.addAction(self.menuWhatIsIt.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        """""

    def kub5(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_KUB5()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kUB5Button.setText(_translate("MainWindow", "КУБ-5"))
        """""
        self.menuMaps.setTitle(_translate("MainWindow", "Карты"))
        self.menuAboutUs.setTitle(_translate("MainWindow", "О нас"))
        self.menuObjects.setTitle(_translate("MainWindow", "Цеха и объекты"))
        self.menuActionGTP.setTitle(_translate("MainWindow", "ГТП"))
        self.menuActionFKhL.setTitle(_translate("MainWindow", "ФХЛ"))
        self.menuDepartments.setTitle(_translate("MainWindow", "Службы"))
        self.menuWhatIsIt.setTitle(_translate("MainWindow", "Что это такое?"))
        self.actionGlobalMap.setText(_translate("MainWindow", "Глобальная"))
        self.actionCPPR.setText(_translate("MainWindow", "ЦППР"))
        self.actionAP.setText(_translate("MainWindow", "АП"))
        self.actionGBK.setText(_translate("MainWindow", "ГБК"))
        self.actionPoligon.setText(_translate("MainWindow", "Полигон"))
        self.actionRaskomandirovka.setText(_translate("MainWindow", "Раскомандировка"))
        self.actionFKhLFirstFloor.setText(_translate("MainWindow", "Первый этаж"))
        self.actionFKhLSecondFloor.setText(_translate("MainWindow", "Второй этаж"))
        self.KIPiA.setText(_translate("MainWindow", "КИПиА"))
        self.SGE.setText(_translate("MainWindow", "СГЭ"))
        self.SGM.setText(_translate("MainWindow", "СГМ"))
        self.actionKaratauMap.setText(_translate("MainWindow", "Каратау"))"""""

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_UPRR()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())